from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from cleanteams.views import *

urlpatterns = patterns('',
    url(r'^invite/?$', InviteView.as_view()),
    url(r'^invite-org/?$', InviteOrganizationView.as_view()),
    url(r'^invite/unsubscribe/(?P<token>\w+)/?$', 'cleanteams.views.unsubscribe'),
    url(r'^invite/(?P<token>\w+)/?$', 'cleanteams.views.invite_check'),
    url(r'^invite-org/(?P<token>\w+)/?$', 'cleanteams.views.referral_check'),
    url(r'^resend-invite/?$', 'cleanteams.views.resend_invite'),
    url(r'^invite-response/(?P<token>\w+)/?$', InviteResponseView.as_view()),
    # url(r'^invite/(?P<token>\w+)/?$', 'cleanteams.views.accept_invite'),
    url(r'^post-message-ajax/?$', 'cleanteams.views.post_message_ajax'),
    url(r'^post-message/?$', PostMessageView.as_view()),
    url(r'^members/?$', CleanTeamMembersView.as_view()),
    url(r'^community-members/?$', CommunityMembersView.as_view()),
    url(r'^level-progress/?$', LevelProgressView.as_view()),
    url(r'^edit/?$', EditCleanTeamView.as_view()),
    url(r'^community/edit/?$', EditCommunityView.as_view()),
    url(r'^main-contact/?$', CleanTeamMainContactView.as_view()),
    url(r'^report-spam/(?P<signature>\w+)/?$', 'cleanteams.views.report_as_spam'),
    url(r'^register-clean-team/?$', RegisterCleanTeamView.as_view()),
    url(r'^register-request-join/?$', RegisterRequestJoinView.as_view()),
    url(r'^send-presentation/?$', CleanTeamPresentationView.as_view()),
    url(r'^follow-team/?$', 'cleanteams.views.follow_team'),
    url(r'^unfollow-team/?$', 'cleanteams.views.unfollow_team'),
    url(r'^ca-request-join/?$', 'cleanteams.views.request_join_clean_team'),
    url(r'^community-membership-request/?$', 'cleanteams.views.community_membership_request'),
    url(r'^member-action/?$', 'cleanteams.views.clean_team_member_action'),
    url(r'^community-member-action/?$', 'cleanteams.views.community_member_action'),
    url(r'^create-team-or-org/?$', TeamOrOrganization.as_view()),
    url(r'^create-community/?$', CreateCommunityView.as_view()),
    url(r'^community/(?P<community_id>\d+)/?$', CommunityView.as_view()),
    url(r'^community-search/?$', 'cleanteams.views.community_search'),
    url(r'^/?$', ViewAllCleanTeams.as_view()),
    url(r'^(?P<ctid>\d+)/?$', CleanTeamView.as_view()),
    url(r'^my-change-network/?$', MyChangeNetwork.as_view()))
